"""Type hints for tensorshare.serialization.utils.py."""

from typing import Any, Dict, Optional

# Save functions from safetensors
def flax_save(tensors: Dict[str, Any], metadata: Optional[Dict[str, str]]) -> bytes: ...
def np_save(tensors: Dict[str, Any], metadata: Optional[Dict[str, str]]) -> bytes: ...
def paddle_save(
    tensors: Dict[str, Any], metadata: Optional[Dict[str, str]]
) -> bytes: ...
def tf_save(tensors: Dict[str, Any], metadata: Optional[Dict[str, str]]) -> bytes: ...
def torch_save(
    tensors: Dict[str, Any], metadata: Optional[Dict[str, str]]
) -> bytes: ...

# Convert functions
def convert_flax_to_safetensors(
    tensors: Dict[str, Any], metadata: Optional[Dict[str, str]]
) -> bytes: ...
def convert_numpy_to_safetensors(
    tensors: Dict[str, Any], metadata: Optional[Dict[str, str]]
) -> bytes: ...
def convert_paddle_to_safetensors(
    tensors: Dict[str, Any], metadata: Optional[Dict[str, str]]
) -> bytes: ...
def convert_tensorflow_to_safetensors(
    tensors: Dict[str, Any], metadata: Optional[Dict[str, str]]
) -> bytes: ...
def convert_torch_to_safetensors(
    tensors: Dict[str, Any], metadata: Optional[Dict[str, str]]
) -> bytes: ...
